kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: vehicles
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vehicles
  # minReplicas: 2
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      # use the metric that you used above: pods/http_requests
      metricName: moleculer_request_per_second
      # target 25000 milli-requests per second,
      # which is 25 request every second
      targetAverageValue: 30000m