apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicles
  labels:
    app: foober-vehicles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foober-vehicles
  template:
    metadata:
      name: vehicles
      labels:
        app: foober-vehicles
    spec:
      containers:
        - image: miksamixa/foober-vehicles:v6
          name: vehicles
          livenessProbe:
            httpGet:
              path: /vehicles/health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 256M
            limits:
              cpu: 200m
              memory: 320M
          env:
            - name: SERVICEDIR
              value: services
            - name: SYNC
              value: "false"
            - name: DB_HOST
              value: vehicles-db-postgresql-ha-pgpool
            - name: DB_USER
              value: dbuser
            - name: DB_PASSWORD
              value: super_secret
          ports:
            - containerPort: 3030