---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-api-gateway
  template:
    metadata:
      name: mt-api-gateway
      labels:
        app: mt-api-gateway
    spec:
      containers:
        - image: miksamixa/mt-api-gateway:v6
          name: moleculer-api-gateway
          resources:
            requests:
              cpu: 50m
              memory: 200M
            limits:
              cpu: 80m
              memory: 200M
          env:
            - name: PORT
              value: "3000"
            - name: SERVICEDIR
              value: services
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: mt-api-gateway
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "api"
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: "mt-managed-cert"
spec:
  rules:
    - host: mt.mihajlo.dev
      http:
        paths:
          - backend:
              serviceName: api-gateway
              servicePort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mt-api-gateway-deployment
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: mt-api-gateway-deployment
  targetCPUUtilizationPercentage: 30
