version: "3.7"
services:

  nats:
    image: nats:2
  
  api-gateway:
    build:
      context: ./api-gateway
    image: master/api-gateway
    environment:
      PORT: 3000
      SERVICEDIR: services
    ports: 
      - "3000:3000"
    depends_on:
      - nats
      - vehicles
      - vehicle_communicator

  postgres:
    image: postgres:12
    environment: 
      POSTGRES_DB: vehicles
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: super_secret

  vehicles:
    build:
      context: ./vehicles
    image: master/vehicles
    environment: 
      SERVICEDIR: services
    depends_on:
      - postgres
  
  mongodb:
    image: mongo:4

  vehicle_communicator:
    build:
      context: ./vehicle-communicator
    image: master/vehicle-communicator
    environment:
      SERVICEDIR: services
    depends_on:
      - mongodb
      - vehicles