version: "3.7"
services:

  nats-client:
    image: nats:2
  
  api-gateway:
    build:
      context: ./api-gateway
    image: master/api-gateway
    environment:
      PORT: 3000
      SERVICEDIR: services
    ports: 
      - "3000:3000"
    depends_on:
      - nats-client
      - vehicles
      - telematics

  postgres:
    image: postgres:12
    environment: 
      POSTGRES_DB: vehicles
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: super_secret

  vehicles:
    build:
      context: ./vehicles
    image: master/vehicles
    environment: 
      SERVICEDIR: services
      DB_HOST: postgres
      DB_USER: dbuser
      DB_PASSWORD: super_secret
      SYNC: 'false'
    depends_on:
      - nats-client
      - postgres
  
  mongodb:
    image: mongo:4

  telematics:
    build:
      context: ./telematics
    image: master/telematics
    environment:
      SERVICEDIR: services
      DB_URL: mongodb://mongodb:27017/thesis
    depends_on:
      - nats-client
      - mongodb
      - vehicles
