{
 "title": "Foober",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Broj kapsula po servisu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Broj kapsula" }
   ],
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container_name=~\"api-gateway|rides|vehicles|telematics\", namespace=\"default\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Broj zahteva po servisu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Broj zahteva u sekundi" }
   ],
   "targets": [
    {
     "expr": "sum(rate(moleculer_request_total{type=\"local\"}[1m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Rides scenario",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Vreme odgovora" }
   ],
   "targets": [
    { "target": "*.gauges.rides-concurrency" }
   ]
  },
  {
   "title": "Messages scenario",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Vreme odgovora" }
   ],
   "targets": [
    { "target": "*.gauges.messages-concurrency" }
   ]
  },
  {
   "title": "Admin scenario",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "Vreme odgovora" }
   ],
   "targets": [
    { "target": "*.gauges.admin-concurrency" }
   ]
  },
  {
   "title": "Rides scenario",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Vreme odgovora" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.rides-latency.p99)"
    },
    {
     "target": "aliasByMetric(*.*.rides-latency.p95)"
    },
    {
     "target": "aliasByMetric(*.*.rides-latency.max)"
    },
    {
     "target": "aliasByMetric(*.*.rides-latency.min)"
    }
   ]
  },
  {
   "title": "Messages scenario",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Vreme odgovora" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.messages-latency.p99)"
    },
    {
     "target": "aliasByMetric(*.*.messages-latency.p95)"
    },
    {
     "target": "aliasByMetric(*.*.messages-latency.max)"
    },
    {
     "target": "aliasByMetric(*.*.messages-latency.min)"
    }
   ]
  },
  {
   "title": "Admin scenario",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Vreme odgovora" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(*.*.admin-latency.p99)"
    },
    {
     "target": "aliasByMetric(*.*.admin-latency.p95)"
    },
    {
     "target": "aliasByMetric(*.*.admin-latency.max)"
    },
    {
     "target": "aliasByMetric(*.*.admin-latency.min)"
    }
   ]
  },
  {
   "title": "Ukupan broj zahteva",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(moleculer_request_total{type=\"local\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Iskorišćenost CPU-a po kontejneru",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=~\"api-gateway|rides|vehicles|telematics\"}[5m])",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}