---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-a
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: pg-a
    fsType: nfs4
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app: mt-postgres
  ports:
    - name: http
      port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: mt-postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: mt-postgres
    spec:
      containers:
        - name: vehicle-db
          image: postgres:12
          resources:
            requests:
              cpu: 200m
              memory: 512M
            limits:
              cpu: 500m
              memory: 768M
          ports:
            - name: http
              containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: vehicles
          env:
            - name: POSTGRES_DB
              value: vehicles
            - name: POSTGRES_USER
              value: dbuser
            - name: POSTGRES_PASSWORD
              value: super_secret
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        resources:
          requests:
            storage: 512Mi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce