---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-vehicles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt-vehicles
  template:
    metadata:
      name: mt-vehicles
      labels:
        app: mt-vehicles
    spec:
      containers:
        - image: miksamixa/mt-vehicles:v5
          name: vehicles
          resources:
            requests:
              cpu: 50m
              memory: 256M
            limits:
              cpu: 100m
              memory: 320M            
          env:
            - name: SERVICEDIR
              value: services
            # - name: SYNC
            #   value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: vehicles
spec:
  clusterIP: None
  selector:
    app: mt-vehicles
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mt-vehicles
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: mt-vehicles
  targetCPUUtilizationPercentage: 60