---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-a
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    pdName: mongo-a
    fsType: nfs4
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  clusterIP: None
  selector:
    app: mt-mongo
  ports:
    - name: http
      port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mt-mongo
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mt-mongo
    spec:
      containers:
        - name: mongo-vehicle-communicator-db
          image: mongo:4
          resources:
            requests:
              cpu: 200m
              memory: 512M
            limits:
              cpu: 500m
              memory: 768M
          ports:
            - name: http
              containerPort: 27017
          volumeMounts:
            - name: mongodata
              mountPath: /data/db
          # readinessProbe:
          #   exec:
          #     command: ["pg_isready", "-d", "vehicles", "-h", "localhost", "-U", "dbuser"]
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 5
          # livenessProbe:
          #   exec:
          #     command: ["pg_isready", "-d", "vehicles", "-h", "localhost", "-U", "dbuser"]
          #   timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: mongodata
      spec:
        resources:
          requests:
            storage: 512Mi
        storageClassName: standard
        accessModes:
          - ReadWriteOnce