kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: telematics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telematics
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      # use the metric that you used above: pods/http_requests
      metricName: moleculer_request_per_second
      # target 25000 milli-requests per second,
      # which is 150 request every second
      targetAverageValue: 50000m