apiVersion: apps/v1
kind: Deployment
metadata:
  name: telematics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foober-telematics
  template:
    metadata:
      name: telematics
      labels:
        app: foober-telematics
    spec:
      containers:
        - image: miksamixa/foober-telematics:v2
          name: telematics
          resources:
            requests:
              cpu: 200m
              memory: 256M
            limits:
              cpu: 300m
              memory: 320M            
          env:
            - name: SERVICEDIR
              value: services
            - name: DB_URL
              value: mongodb://telematics-db-mongodb-replicaset-client:27017/telematics?replicaSet=rs0