apiVersion: v1
kind: Service
metadata:
  name: telematics
  labels:
    name: telematics
spec:
  selector:
    app: foober-telematics
  ports:
    - name: metrics
      port: 3030
      targetPort: 3030