kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      # use the metric that you used above: pods/http_requests
      metricName: moleculer_request_per_second
      # target 50000 milli-requests per second,
      # which is 50 request every second
      targetAverageValue: 25000m