apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: foober-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foober-api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        app: foober-api-gateway
    spec:
      containers:
        - image: miksamixa/foober-api-gateway:v2
          name: api-gateway
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 200M
            limits:
              cpu: 200m
              memory: 200M
          env:
            - name: PORT
              value: "3000"
            - name: SERVICEDIR
              value: services
          ports:
            - containerPort: 3000
            - containerPort: 3030