apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "api"
  # annotations:
  #   ingress.gcp.kubernetes.io/pre-shared-cert: "foober-managed-cert"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: api-gateway
              servicePort: 80