kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: rides
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rides
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      # use the metric that you used above: pods/http_requests
      metricName: moleculer_request_per_second
      # target 20000 milli-requests per second,
      # which is 20 request every second
      targetAverageValue: 50000m