apiVersion: apps/v1
kind: Deployment
metadata:
  name: rides
  labels:
    app: foober-rides
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foober-rides
  template:
    metadata:
      name: rides
      labels:
        app: foober-rides
    spec:
      containers:
        - image: miksamixa/foober-rides:v2
          name: rides
          livenessProbe:
            httpGet:
              path: /rides/health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 256M
            limits:
              cpu: 200m
              memory: 320M
          env:
            - name: SERVICEDIR
              value: services
            - name: SYNC
              value: "false"
            - name: DB_HOST
              value: rides-db-postgresql-ha-pgpool
            - name: DB_USER
              value: dbuser
            - name: DB_PASSWORD
              value: super_secret
          ports:
            - containerPort: 3030